### PR TITLE
Fix various issues

### LINKED ISSUE #7: Doesn't stop on first match
The program keeps on trying all the passwords until the wordlist file ends or until the pipe is closed when the input ceases. This is an issue especially because

1. It wastes time, trying passwords that do not need to be tried
2. It may never terminate if the generator used does not terminate on it's own (for example hashcat with stdout in brute force mode)

Test case

```bash
echo "This is a secret" > secret.txt
ccrypt -e -K p4ssw0rd secret.txt
cptcrypt-ng -w /usr/share/seclists//Passwords/Leaked-Databases/rockyou-75.txt
```

This will run through all words in the list. (check against `wc -l`)

If you have a substancial wordlist and you put the test case at the very start (say the entire rockyou database and your password is 123456), then it will run through all 14M passwords.

```text
cptcracker-ng -w [...]/SecLists/Passwords/Leaked-Databases/rockyou.txt -f testcrypt.txt.cpt

 ~ CPT Cracker-ng v2.0.0-dev ~
 - File......: testcrypt.txt.cpt
 - Generator.: rockyou.txt
 . Worked at 421,948 pwd/sec
   Combinations: 14,346,259
   Working time: 34 sec
 + Password found: p4ssw0rd
   HEXA[ 70 34 73 73 77 30 72 64 ]
 ^ Ex(c)iting.
                                                                                                                                                                   [ 1m-25,898s ]
grep -n "p4ssw0rd" [...]/SecLists/Passwords/Leaked-Databases/rockyou.txt
40860:p4ssw0rd
[...]
wc -l [...]SecLists/Passwords/Leaked-Databases/rockyou.txt
14344391[...]/SecLists/Passwords/Leaked-Databases/rockyou.txt
```

With 422k pwd/s it shouldn't take 34 seconds to reach the 41000th line but rather about 1 second.

### PR DESCRIPTION
**Pull request by FalcoGer**
Fixes
#7 
#8 
#9

### CODE REVIEW

**Comment by FalcoGer** [comment]
mind you, I didn't test extensively and I didn't touch the zip stuff at all.

**Comment by FalcoGer** [comment]
should I have done 3 PRs?

**Comment by FalcoGer** [comment]
let me redo this

**Comment by BoboTiG** [comment]
It's ok for me :)

**Pull request closed without merging**
