### PR TITLE
fixed error: ISO C++ forbids comparison between pointer and integer

### PR DESCRIPTION
**Pull request by Zenaker**

### CODE REVIEW

**Comment by BoboTiG** [comment]
I just compiled it with `make zip` and it did not show the warning/error. How did you catch it?

**Comment by ffontaine** [comment]
I was able to reproduce this build failure with 
`gcc (Debian 10.2.1-6) 10.2.1 20210110`

**Comment by BoboTiG** [comment]
@ffontaine could you copy paste the whole command lines + the output please?

**Comment by ffontaine** [comment]
Sure, here you go, from a fresh git clone, here is the result, due to hardocoded `-Werror`: 

```
make zip
 + Building zip module ...
make -C src/ zip clean DEBUG=0
make[1]: Entering directory '/root/test/cracker-ng/src'
g++ -O3 -ffast-math -march=native -D_FILE_OFFSET_BITS=64 -Wfatal-errors -Werror -Wall -W -pedantic -Wextra -Wunused -Wformat=2 -Weffc++ -Wpadded -fexceptions -c shared/functions.cc -o zipfunctions.o -DZIP
g++ -O3 -ffast-math -march=native -D_FILE_OFFSET_BITS=64 -Wfatal-errors -Werror -Wall -W -pedantic -Wextra -Wunused -Wformat=2 -Weffc++ -Wpadded -fexceptions -c shared/stats.cc
g++ -O3 -ffast-math -march=native -D_FILE_OFFSET_BITS=64 -Wfatal-errors -Werror -Wall -W -pedantic -Wextra -Wunused -Wformat=2 -Weffc++ -Wpadded -fexceptions -c shared/gui.cc -o zipgui.o -DZIP
g++ -O3 -ffast-math -march=native -D_FILE_OFFSET_BITS=64 -Wfatal-errors -Werror -Wall -W -pedantic -Wextra -Wunused -Wformat=2 -Weffc++ -Wpadded -fexceptions -c zip/read.cc
In function ‘void swap_lfh(const local_file_header&, local_file_header_light*)’,
    inlined from ‘void swap_lfh(const local_file_header&, local_file_header_light*)’ at zip/read.cc:14:6:
zip/read.cc:28:10: error: ‘char* strncpy(char*, const char*, size_t)’ specified bound 512 equals destination size [-Werror=stringop-truncation]
   28 |   strncpy(lfh->file_name, local_lfh.file_name, 512);
      |   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
make[1]: *** [Makefile:62: read.o] Error 1
make[1]: Leaving directory '/root/test/cracker-ng/src'
make: *** [Makefile:21: zip] Error 2
```

After removing `-Werror` from `src/Makefile`, here is the result:
```
make zip
+ Building zip module ...
make -C src/ zip clean DEBUG=0
make[1]: Entering directory '/root/test/cracker-ng/src'
g++ -O3 -ffast-math -march=native -D_FILE_OFFSET_BITS=64 -Wfatal-errors -Wall -W -pedantic -Wextra -Wunused -Wformat=2 -Weffc++ -Wpadded -fexceptions -c zip/read.cc
In function ‘void swap_lfh(const local_file_header&, local_file_header_light*)’,
    inlined from ‘void swap_lfh(const local_file_header&, local_file_header_light*)’ at zip/read.cc:14:6:
zip/read.cc:28:10: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 512 equals destination size [-Wstringop-truncation]
   28 |   strncpy(lfh->file_name, local_lfh.file_name, 512);
      |   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘void swap_lfh(const local_file_header&, local_file_header_light*)’,
    inlined from ‘void swap_lfh(const local_file_header&, local_file_header_light*)’ at zip/read.cc:14:6,
    inlined from ‘void read_ng::read_local_file_header(std::ifstream&, local_file_header_light*, bool, bool)’ at zip/read.cc:306:11:
zip/read.cc:28:10: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 512 equals destination size [-Wstringop-truncation]
   28 |   strncpy(lfh->file_name, local_lfh.file_name, 512);
      |   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘void swap_lfh(const local_file_header&, local_file_header_light*)’,
    inlined from ‘void swap_lfh(const local_file_header&, local_file_header_light*)’ at zip/read.cc:14:6,
    inlined from ‘void read_ng::read_local_file_header(std::ifstream&, local_file_header_light*, bool, bool)’ at zip/read.cc:301:13:
zip/read.cc:28:10: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 512 equals destination size [-Wstringop-truncation]
   28 |   strncpy(lfh->file_name, local_lfh.file_name, 512);
      |   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘void swap_lfh(const local_file_header&, local_file_header_light*)’,
    inlined from ‘void swap_lfh(const local_file_header&, local_file_header_light*)’ at zip/read.cc:14:6,
    inlined from ‘void read_ng::read_local_file_header(std::ifstream&, local_file_header_light*, bool, bool)’ at zip/read.cc:298:14:
zip/read.cc:28:10: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 512 equals destination size [-Wstringop-truncation]
   28 |   strncpy(lfh->file_name, local_lfh.file_name, 512);
      |   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
g++ -O3 -ffast-math -march=native -D_FILE_OFFSET_BITS=64 -Wfatal-errors -Wall -W -pedantic -Wextra -Wunused -Wformat=2 -Weffc++ -Wpadded -fexceptions -c zip/puff.cc
g++ -O3 -ffast-math -march=native -D_FILE_OFFSET_BITS=64 -Wfatal-errors -Wall -W -pedantic -Wextra -Wunused -Wformat=2 -Weffc++ -Wpadded -fexceptions -c shared/cracker.cc -o zipcracker.o -DZIP
In file included from shared/cracker.cc:13:
shared/./cracker.h: In member function ‘bool Cracker::csgets(char**, char*&, const size_t&)’:
shared/./cracker.h:115:15: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
  115 |   return next != '\0';
      |          ~~~~~^~~~~~~
compilation terminated due to -Wfatal-errors.
make[1]: *** [Makefile:65: zipcracker.o] Error 1
make[1]: Leaving directory '/root/test/cracker-ng/src'
make: *** [Makefile:21: zip] Error 2
```

**Comment by BoboTiG** [comment]
I do not reproduce because my Mac is using clang. And it seems this is not a problem, there is not even a warning.
I will wait for a reproductible env before merging and fixing all warnings (it should not be long).

**Comment by BoboTiG** [comment]
Reproduced, thanks @Zenaker and @ffontaine 👍

**Comment by BoboTiG** [comment]
The second warning is fixed with f15b7592e03af7e92cdab725029514588b6f73a7, you should be good to compile :)

**Pull request merged**
